# config_example.toml
[database]
host = "localhost"
port = 5432
user = "root"
password = "password"
dbname = "equity_research"

[anthropic]
api_key = "your_anthropic_api_key"
model = "claude-3-opus-20240229"

[API]
API_KEY = "your_api_key"

[app]
reports_dir = "reports"